### ISSUE TITLE
UI Design überarbeiten

### ISSUE THREAD

**Issue by th3gumm3l** [LianEifert/M213-Projektarbeit#2]
- Wireframe als Vorlage benutzen
- Hintergrund passend zum Spiel
- Labels als Spielleitung / Erklärung
- Element Namen sollen nicht komplex sein
- Responisve Design

**Comment by C-x-3-3-0** [comment]
![WhatsApp Image 2022-05-26 at 10 04 58 AM (2)](https://user-images.githubusercontent.com/89629020/170447530-4cffc384-a211-40c8-b582-7071de70d778.jpeg)
![WhatsApp Image 2022-05-26 at 10 04 58 AM (1)](https://user-images.githubusercontent.com/89629020/170447533-c218aab9-edf8-4040-a0fe-4e619c54cc40.jpeg)
![WhatsApp Image 2022-05-26 at 10 04 58 AM](https://user-images.githubusercontent.com/89629020/170447535-da53d6da-bbf0-4444-a8ac-58f7a0b00df2.jpeg)
Grobe UI Design mit Wireframe
